In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class MyNeuralNet(nn.Module):
    def __init__(self, input_size, n_nodes, output_size):
        super(MyNeuralNet, self).__init__()
        self.operationOne = nn.Linear(input_size, n_nodes)
        self.operationTwo = nn.Linear(n_nodes, output_size)
    def forward(self, x):
        x = F.relu(self.operationOne(x))
        x = self.operationTwo(x)
        x = F.sigmoid(x)
        return x

In [13]:
my_network = MyNeuralNet(input_size = 3, n_nodes = 2, output_size = 1)

Understanding Tensors

In [14]:
import torch
first_order_tensor = torch.tensor([1, 2, 3])
print(first_order_tensor)

tensor([1, 2, 3])


In [15]:
print(first_order_tensor[0])

tensor(1)


In [16]:
print(first_order_tensor[0:2])

tensor([1, 2])


In [17]:
print(first_order_tensor[1:])

tensor([2, 3])


In [18]:
second_order_tensor = torch.tensor([ [ 11, 22, 33 ],
 [ 21, 22, 23 ]
 ])
print(second_order_tensor)

tensor([[11, 22, 33],
        [21, 22, 23]])


In [20]:
print(second_order_tensor[0, 1])

tensor(22)


In [21]:
fourth_order_tensor = torch.tensor(
[
 [
 [
 [1111, 1112],
 [1121, 1122]
 ],
 [
 [1211, 1212],
 [1221, 1222]
 ]
 ],
 [
 [
 [2111, 2112],
 [2121, 2122]
 ],
 [
 [2211, 2212],
 [2221, 2222]
 ]
 ]
])


In [22]:
my_tensor = torch.tensor([1, 2, 3, 4, 5])
print(my_tensor.size())

torch.Size([5])


In [23]:
my_tensor = torch.tensor([[11, 12, 13], [21, 22, 23]])
print(my_tensor.size())

torch.Size([2, 3])


In [24]:
print(fourth_order_tensor.size())

torch.Size([2, 2, 2, 2])


In [25]:
random_tensor = torch.rand([4, 2])
print(random_tensor)

tensor([[0.8849, 0.2496],
        [0.0906, 0.8850],
        [0.3370, 0.4994],
        [0.2537, 0.1573]])


In [26]:
random_tensor.view([2, 4])

tensor([[0.8849, 0.2496, 0.0906, 0.8850],
        [0.3370, 0.4994, 0.2537, 0.1573]])

In [27]:
random_tensor = torch.rand([4, 2, 4])
random_tensor.view([2, 4, -1])

tensor([[[0.0420, 0.2747, 0.9238, 0.6606],
         [0.8135, 0.1987, 0.3658, 0.7605],
         [0.1217, 0.5256, 0.4733, 0.1900],
         [0.7616, 0.0601, 0.1716, 0.6475]],

        [[0.4079, 0.0604, 0.9344, 0.1486],
         [0.8861, 0.7199, 0.5216, 0.0384],
         [0.9297, 0.8486, 0.2294, 0.3931],
         [0.7904, 0.9229, 0.3076, 0.5926]]])

In [28]:
random_tensor.view([2, -1, 4])

tensor([[[0.0420, 0.2747, 0.9238, 0.6606],
         [0.8135, 0.1987, 0.3658, 0.7605],
         [0.1217, 0.5256, 0.4733, 0.1900],
         [0.7616, 0.0601, 0.1716, 0.6475]],

        [[0.4079, 0.0604, 0.9344, 0.1486],
         [0.8861, 0.7199, 0.5216, 0.0384],
         [0.9297, 0.8486, 0.2294, 0.3931],
         [0.7904, 0.9229, 0.3076, 0.5926]]])

In [29]:
x = torch.tensor([5, 3])
y = torch.tensor([3, 2])
torch.add(x, y)

tensor([8, 5])

In [30]:
torch.sub(x, y)

tensor([2, 1])

In [32]:
torch.mul(x, y)

tensor([15,  6])

In [34]:
x + y

tensor([8, 5])

In [35]:
torch.div(x, y)

tensor([1, 1])

In [36]:
x.dtype

torch.int64

In [37]:
y.dtype

torch.int64

In [38]:
x_float = torch.tensor([5, 3], dtype = torch.float32)
y_float = torch.tensor([3, 2], dtype = torch.float32)
print(x_float / y_float)

tensor([1.6667, 1.5000])


In [39]:
torch.FloatTensor([5, 3])

tensor([5., 3.])

In [40]:
x.type(torch.DoubleTensor)

tensor([5., 3.], dtype=torch.float64)

Importing our dataset as a PyTorch Tensor

In [41]:
import numpy as np
admit_data = np.genfromtxt('admit_status.csv', delimiter = ',', skip_header = 1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [42]:
admit_tensor = torch.from_numpy(admit_data)
print(admit_tensor)

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)


Training neural networks in PyTorch

In [47]:
x_train = admit_tensor[:300, 1:].float()
y_train = admit_tensor[:300, 0].float()
x_test = admit_tensor[300:, 1:].float()
y_test = admit_tensor[300:, 0].float()

In [48]:
criterion = nn.BCELoss()

In [49]:
optimizer = torch.optim.SGD(my_network.parameters(), lr=0.01)

In [55]:
for epoch in range(100):
    y_pred = my_network(x_train)
    loss_score = criterion(y_pred, y_train)
    print('epoch: ', epoch, 'loss: ', loss_score)
    
    optimizer.zero_grad()
    loss_score.backward()
    optimizer.step()

epoch:  0 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  1 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  2 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  3 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  4 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  5 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  6 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  7 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  8 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  9 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  10 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  11 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  12 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  13 loss:  tensor(18.4207, grad_fn=<BinaryCrossEntropyBackward>)
ep