### Layers : Fundamental blocks of Neural Network

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable
from torchvision import models
from torchvision.datasets import ImageFolder

In [2]:
linear_layer = Linear(in_features=5,out_features=3,bias=True)

In [3]:
inp = Variable(torch.randn(1,5))
linear_layer(inp)

tensor([[ 0.3152, -0.0554, -0.1452]], grad_fn=<ThAddmmBackward>)

In [4]:
linear_layer.weight

Parameter containing:
tensor([[-0.0315, -0.0039,  0.4212,  0.3013, -0.0821],
        [ 0.2441, -0.1082,  0.3844,  0.1104, -0.4308],
        [-0.1339, -0.2200, -0.0068, -0.3500,  0.2612]], requires_grad=True)

In [5]:
linear_layer.bias

Parameter containing:
tensor([ 0.3274,  0.4079, -0.0899], requires_grad=True)

In [6]:
linear_layer = Linear(5,3)
linear_layer_2 = Linear(3,2)
linear_layer_2(linear_layer(inp))

tensor([[-0.1576,  0.3464]], grad_fn=<ThAddmmBackward>)

In [7]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[0.4106, 0.0803, 0.2885, 0.2869, 0.6083]], grad_fn=<ThAddmmBackward>)

In [8]:
myLayer.weight

Parameter containing:
tensor([[ 0.1218, -0.0985, -0.3086, -0.2921,  0.2529,  0.2500,  0.3018, -0.2215,
          0.1692,  0.1859],
        [ 0.1042,  0.1702, -0.0632,  0.1657, -0.2838, -0.1824, -0.2449, -0.0798,
         -0.2923, -0.0322],
        [-0.1495, -0.1981, -0.0228,  0.0887,  0.0063,  0.1339,  0.0960,  0.2709,
         -0.1094,  0.2661],
        [ 0.3035,  0.0564, -0.2110,  0.2329, -0.3028,  0.1364, -0.0546, -0.0555,
          0.1255, -0.2914],
        [-0.1702, -0.1900, -0.3047,  0.1264, -0.0478,  0.1690,  0.1096,  0.1911,
          0.0297, -0.1811]], requires_grad=True)

In [9]:
myLayer.bias

Parameter containing:
tensor([ 0.3022,  0.2824, -0.0020, -0.0711,  0.2299], requires_grad=True)

### PyTorch Non-linear Activations

In [10]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)

tensor([[1., 2., 0., 0.]])

In [11]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### Neural Network 

In [12]:
class MyFirstNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

In [13]:
my_network = MyFirstNetwork(input_size = 3, hidden_size = 2, output_size = 1)

### Loss

In [14]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

In [15]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [16]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### Optimizer

In [21]:
# for demo
optimizer = torch.optim.SGD(my_network.parameters(), lr = 0.01)
for input, target in torch.utils.data.Dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

TypeError: 'type' object is not iterable